# Generated by Django 4.2.16 on 2026-05-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='chat_notifi_recipie_43ccca_idx',
            old_name='chat_notif_recipie_idx',
        ),
    ]
