# Generated by Django 5.1.4 on 2025-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0002_bikehardware_battery_level_bikehardware_factory_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikehardware',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from this specific bike', max_digits=10),
        ),
    ]
