# Generated by Django 5.1.4 on 2025-05-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0003_bikehardware_total_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikehardware',
            name='total_earnings',
        ),
        migrations.AddField(
            model_name='bikes',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from this specific bike', max_digits=10),
        ),
    ]
