# Generated by Django 5.1.4 on 2025-05-31 04:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0004_remove_bikehardware_total_earnings_and_more'),
        ('Owner', '0004_remove_ownerprofile_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikehardware',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bike Hardware', 'verbose_name_plural': 'Bike Hardware'},
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='signal_strength',
            field=models.IntegerField(blank=True, help_text='Signal strength in dBm', null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='unlock_code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikehardware',
            name='battery_level',
            field=models.IntegerField(default=100, help_text='Battery percentage 0-100'),
        ),
        migrations.AlterField(
            model_name='bikehardware',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikehardware',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='bike_status',
            field=models.CharField(choices=[('available', 'Available for Rent'), ('rented', 'Currently Rented'), ('reserved', 'Reserved'), ('disabled', 'Temporarily Disabled'), ('maintenance', 'Under Maintenance')], default='disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='hardware',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bike', to='Bikes.bikehardware'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='hardware_status',
            field=models.CharField(choices=[('active', 'Active and Ready'), ('inactive', 'Inactive or Unavailable'), ('maintenance', 'Under Maintenance'), ('locked', 'Locked'), ('unlocked', 'Unlocked'), ('offline', 'Hardware Offline'), ('low_battery', 'Low Battery')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bikehardware',
            index=models.Index(fields=['serial_number'], name='Bikes_bikeh_serial__931630_idx'),
        ),
        migrations.AddIndex(
            model_name='bikehardware',
            index=models.Index(fields=['is_assigned', 'is_online'], name='Bikes_bikeh_is_assi_7db019_idx'),
        ),
        migrations.AddIndex(
            model_name='bikehardware',
            index=models.Index(fields=['latitude', 'longitude'], name='Bikes_bikeh_latitud_976c14_idx'),
        ),
        migrations.AddIndex(
            model_name='bikes',
            index=models.Index(fields=['is_available', 'is_active'], name='Bikes_bikes_is_avai_205597_idx'),
        ),
        migrations.AddIndex(
            model_name='bikes',
            index=models.Index(fields=['owner', 'bike_status'], name='Bikes_bikes_owner_i_4b31e6_idx'),
        ),
    ]
