# Generated by Django 5.1.4 on 2025-05-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0005_alter_bikehardware_options_bikehardware_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
