# Generated by Django 5.1.4 on 2025-06-12 07:44

import Bikes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0006_bikes_bike_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the bike', null=True, upload_to=Bikes.models.bike_image_upload_path),
        ),
    ]
