# Generated by Django 5.0.4 on 2026-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0007_bikes_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
