# Generated by Django 5.0.4 on 2026-04-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0008_bikes_rating_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikehardware',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bikehardware',
            name='Bikes_bikeh_serial__931630_idx',
        ),
        migrations.RemoveIndex(
            model_name='bikehardware',
            name='Bikes_bikeh_is_assi_7db019_idx',
        ),
        migrations.RemoveIndex(
            model_name='bikehardware',
            name='Bikes_bikeh_latitud_976c14_idx',
        ),
        migrations.RemoveIndex(
            model_name='bikes',
            name='Bikes_bikes_is_avai_205597_idx',
        ),
        migrations.RemoveIndex(
            model_name='bikes',
            name='Bikes_bikes_owner_i_4b31e6_idx',
        ),
        migrations.RemoveField(
            model_name='bikehardware',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bikehardware',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='bikehardware',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='bikehardware',
            name='signal_strength',
        ),
        migrations.RemoveField(
            model_name='bikehardware',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='bike_address',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='bike_image',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='unlock_code_generated_at',
        ),
        migrations.AlterField(
            model_name='bikehardware',
            name='battery_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='bikehardware',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bikehardware',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='bike_status',
            field=models.CharField(choices=[('available', 'Available for Rent'), ('rented', 'Currently Rented'), ('reserved', 'Reserved'), ('disabled', 'Temporarily Disabled')], default='disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='hardware',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bike', to='Bikes.bikehardware'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='hardware_status',
            field=models.CharField(choices=[('active', 'Active and Ready'), ('inactive', 'Inactive or Unavailable'), ('maintenance', 'Under Maintenance'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
