# Generated by Django 5.0.4 on 2026-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0009_alter_bikehardware_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the bike', null=True, upload_to='bike_images/'),
        ),
    ]
