# Generated by Django 4.2.16 on 2026-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0010_bikes_bike_address_bikes_bike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bikes',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
