# Generated by Django 5.1.4 on 2025-06-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
