# Generated by Django 5.0.4 on 2026-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0002_alter_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
