# Generated by Django 5.0.4 on 2026-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0003_userprofile_apple_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
