# Generated by Django 5.0.4 on 2026-04-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0004_userprofile_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rider_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rider_rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
