# Generated by Django 5.0.4 on 2026-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rider', '0005_userprofile_rider_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apple_sub',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_payment_method',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rider_rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rider_rating_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(),
        ),
    ]
