# Generated by Django 5.1.4 on 2025-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from all bikes own', max_digits=10),
        ),
    ]
