# Generated by Django 5.1.4 on 2025-05-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_ownerprofile_default_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='default_payment_method',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='stripe_customer_id',
        ),
    ]
