# Generated by Django 5.1.4 on 2025-06-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_remove_ownerprofile_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
