# Generated by Django 5.0.4 on 2026-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_ownerprofile_apple_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
