# Generated by Django 5.0.4 on 2026-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0009_ownerprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='apple_sub',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='total_earnings',
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='owner/profile/'),
        ),
    ]
