# Generated by Django 5.0.4 on 2026-04-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0010_remove_ownerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
