# Generated by Django 5.0.4 on 2026-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0011_ownerprofile_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
