# Generated by Django 4.2.16 on 2026-05-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0013_ownerprofile_address_alter_ownerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stripe_transfer_id', models.CharField(max_length=100)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(choices=[('instant', 'Instant'), ('standard', 'Standard')], default='instant', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='Owner.ownerprofile')),
            ],
        ),
    ]
