# Generated by Django 5.1.4 on 2025-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0002_bikehardware_battery_level_bikehardware_factory_key_and_more'),
        ('Owner', '0001_initial'),
        ('Rider', '0001_initial'),
        ('Trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('ontrip', 'On Trip'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='waiting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'trip_date'], name='Trip_trip_status_ca6251_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['renter', 'status'], name='Trip_trip_renter__bfa509_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['bike_owner', 'status'], name='Trip_trip_bike_ow_b0d5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['bike', 'status'], name='Trip_trip_bike_id_e4aa2c_idx'),
        ),
    ]
