# Generated by Django 5.0.4 on 2026-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0002_trip_destination_address_trip_origin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rider_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='rider_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
