# Generated by Django 5.0.4 on 2026-04-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_trip_rider_rating_trip_rider_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='owner_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='owner_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
