# Generated by Django 5.0.4 on 2026-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_trip_owner_rating_trip_owner_review'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trip',
            name='Trip_trip_status_ca6251_idx',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='Trip_trip_renter__bfa509_idx',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='Trip_trip_bike_ow_b0d5d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='trip',
            name='Trip_trip_bike_id_e4aa2c_idx',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin_address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='owner_rating',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='owner_review',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rider_rating',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rider_review',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stripe_transfer_id',
        ),
        migrations.AlterField(
            model_name='trip',
            name='code_generated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('started', 'Started'), ('canceled', 'Canceled'), ('ontrip', 'On Trip'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
