# Generated by Django 5.0.4 on 2026-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0005_remove_trip_trip_trip_status_ca6251_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
