# Generated by Django 5.1.4 on 2025-05-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0004_remove_bikehardware_total_earnings_and_more'),
        ('Owner', '0002_ownerprofile_total_earnings'),
        ('Rider', '0001_initial'),
        ('Riderequest', '0003_alter_ride_request_options_ride_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_request',
            name='owner_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='payment_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='platform_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='ride_request',
            index=models.Index(fields=['payment_status'], name='Riderequest_payment_18b735_idx'),
        ),
    ]
