# Generated by Django 5.1.4 on 2025-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riderequest', '0004_ride_request_owner_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_request',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
