# Generated by Django 5.2.1 on 2025-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riderequest', '0005_ride_request_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_request',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='origin_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
