# Generated by Django 5.1.4 on 2025-05-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0004_remove_bikehardware_total_earnings_and_more'),
        ('Owner', '0004_remove_ownerprofile_default_payment_method_and_more'),
        ('Rider', '0001_initial'),
        ('Riderequest', '0006_ride_request_destination_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride_request',
            index=models.Index(fields=['Rider', 'bike', 'status'], name='Riderequest_Rider_i_02f33a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ride_request',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('Rider', 'bike'), name='unique_pending_request_per_rider_bike'),
        ),
        migrations.AddConstraint(
            model_name='ride_request',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('Rider',), name='unique_pending_request_per_rider'),
        ),
    ]
