# Generated by Django 5.0.4 on 2026-04-21 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0009_alter_bikehardware_options_and_more'),
        ('Riderequest', '0008_alter_ride_request_requested_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride_request',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ride_request',
            name='unique_pending_request_per_rider_bike',
        ),
        migrations.RemoveConstraint(
            model_name='ride_request',
            name='unique_pending_request_per_rider',
        ),
        migrations.RemoveIndex(
            model_name='ride_request',
            name='Riderequest_status_b2b626_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride_request',
            name='Riderequest_Rider_i_95bd60_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride_request',
            name='Riderequest_Owner_i_79c343_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride_request',
            name='Riderequest_payment_18b735_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride_request',
            name='Riderequest_Rider_i_02f33a_idx',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='default_payment_method',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='origin_address',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='owner_earnings',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='payment_processed_at',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='platform_commission',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='ride_request',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='ride_request',
            name='temp_request_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bikes.bikes'),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='payment_type',
            field=models.CharField(blank=True, default='card', max_length=50),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='requested_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
