# Generated by Django 5.0.4 on 2026-05-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riderequest', '0009_alter_ride_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_request',
            name='destination_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='origin_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
